Tutorial
mikel-egana-aranguren/TFG-KG-RelacionesClientelares pull request #26
Opened 2022-06-01 13:19 UTC by JonAnderAsua

Primer tutorial en el README sobre como ejecutar el programa.

2022-06-01 14:32 UTC, mikel-egana-aranguren commented on README.md
>  Readme honetan programa hau nola konfigutatzen eta exekutatzen den azaltzen da. Adibide bezala 'la_donacion' proiektua hartu da.
En MarkDown despues de titulo (#, ##, ###, ...) siempre linea vacia

2022-06-01 14:33 UTC, mikel-egana-aranguren commented on README.md
>  Readme honetan programa hau nola konfigutatzen eta exekutatzen den azaltzen da. Adibide bezala 'la_donacion' proiektua hartu da.
README

2022-06-01 14:34 UTC, mikel-egana-aranguren commented on README.md
>  - [Yaml fitxategiaren konfigurazioa](#yaml-fitxategiaren-konfigurazioa)
YAML

2022-06-01 14:34 UTC, mikel-egana-aranguren commented on README.md
>  - [Programaren exekuzioa](#programaren_exekuzioa)
Anchor hau ez dabil

2022-06-01 14:36 UTC, mikel-egana-aranguren commented on README.md
>  - Graphdb instantzia bat martxan edukitzea. Honetarako jarraitu _Graphdb_ berak daukan [tutoriala]().
tutorialaren URL-a falta da. 

Zein Python bertsio behar da?

2022-06-01 14:37 UTC, mikel-egana-aranguren commented on README.md
>  ```
--recurse-submodules?
Zein branch erabili behar da?

2022-06-01 14:41 UTC, mikel-egana-aranguren commented on README.md
>  Behin aurrebaldintza guztiak bete direnean konfigurazioaren hasi ahal da, horretarako [yaml fitxategi bat](https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/blob/develop/doc/conf
Behin aurrebaldintza guztiak bete direnean konfigurazioarekin hasi ahal da. Horretarako [yaml fitxategi bat](https://github.com/mikel-egana-aranguren/TFG-KG-RelacionesClientelares/blob/develop/doc/config.yml) aurkitzen da *doc* karpeta barnean hurrengo parametroekin

2022-06-01 14:42 UTC, mikel-egana-aranguren commented on README.md
>  - _validate_: Programaren funtzionamendu egokia bermatzeko testen _path-a_.
Datuak balioztatzeko da, ez programaren funtzionamendua

2022-06-01 14:43 UTC, mikel-egana-aranguren commented on README.md
>  - _named_graph_: Tripleen elementu bakoitzak izango duen URI basea.
Ez. Named Graph GraphDB barruan ze "Poltsan" joango diren datuak dira, ez URI basea

2022-06-01 14:47 UTC, mikel-egana-aranguren requested changes
A partir de la linea 25 no me deja poner comments, ya lo hare de otra manera. Haz esos cambios y vuelve a hacer un commit y push a este branch, me aparecera lo nuevo en el pull request

2022-06-01 14:52 UTC, mikel-egana-aranguren commented
- "rdf_output: Tripeekin" -> "rdf_output: Tripleekin"
- "argitaratuko du" -> "argitaratuko ditu"
- "Programaren froga" no entiendo para que sirve
- La opcion Triple Store que formato tiene? Por lo que veo has puesto una URL con un  formato que solo funciona con GraphDB. Tiene que ser un formato que a traves de SPARQL se puedan meter los datos en cualquier Triple Store (todas respetan el estandar SPARQL). entonces tambien tienes que poner como requisito de "Run" que sea un programa que mete los datos a traves de SPARQL (Para que cualquier pueda hacer un programa propio)
- Egilea hasieran ipini
- Proiektu berri bat egiteko zer egin behar dudan azaldu. Adibidez, zer egin behar du "Run" ataleko programak nire programa sortzen badut?
- Orokorrean: https://bulldogjob.com/readme/how-to-write-a-good-readme-for-your-github-project

2022-06-01 15:10 UTC, mikel-egana-aranguren commented
LOL

![image](https://user-images.githubusercontent.com/3883671/171438005-7dedbd62-19cd-41b2-b4bb-7a24446a9ad8.png)

2022-06-02 10:47 UTC, JonAnderAsua commented
Aldaketak egin dira, bota beste begirada bat mesedez,

2022-06-04 17:00 UTC, mikel-egana-aranguren commented on README.md
> +README honetan programa hau nola konfiguratzen eta exekutatzen den azaltzen da. Programa honek parametro batzuk pasatu ostean era automatiko batean eta _SPARQL_ eskaeri esker datu multzo bat _triple
eskaerei

2022-06-04 17:00 UTC, mikel-egana-aranguren commented on README.md
> +README honetan programa hau nola konfiguratzen eta exekutatzen den azaltzen da. Programa honek parametro batzuk pasatu ostean era automatiko batean eta _SPARQL_ eskaeri esker datu multzo bat _triple
Eta datuak transformatzen ditu

2022-06-04 17:04 UTC, mikel-egana-aranguren commented on README.md
> +- _validate_: Datuen balioztasuna bermatzen duen testen _path-a_.
SHACL testen path-a

2022-06-04 17:05 UTC, mikel-egana-aranguren commented on README.md
> +- _triple_store_: Tripleak igo nahi diren _triple storearen_ URIa, ez da beharrezkoa GraphDb instantzia baten URI bat izatea, hau da, SPARQL eskaerak onartzen dituen instantzia baten URIa jarri behar
URI -> URL

2022-06-04 17:08 UTC, mikel-egana-aranguren commented on README.md
>  python3 /procesSource/source/ejecutador.py la_donacion
![image](https://user-images.githubusercontent.com/3883671/172017854-bf14e948-bb13-41ec-b94b-8f26f1fb6ac3.png)

tienes un path tuyo metido a mano!

2022-06-05 10:24 UTC, JonAnderAsua commented
Ya he hecho las correcciones que me has dicho... Lo de no poner mi path absoluto también.

2022-06-08 13:49 UTC, merged